# Generated by Django 3.0.5 on 2020-06-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200618_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('chinchilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chinchilla')),
            ],
        ),
    ]
